apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: cronus-pipeline
description: cronus web-server application delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: []
 - targetId: staging
   profiles: []
 - targetId: prod
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: dev cluster
gke:
  cluster: projects/cicd-vog-togke/locations/us-central1/clusters/dev
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/cicd-vog-togke/locations/us-central1/clusters/staging
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/cicd-vog-togke/locations/us-central1/clusters/prod
